spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webapplication
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: developer@me123

  mail:
    host: smtp.gmail.com
    port: 587
    username: hackestone@gmail.com
    password: iabs zkjq xcyc tqjm
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true  
            
server:
  port: 8890

email:
  enable: true
  to: bhoomikahm133@gmail.com
  from: hackestone@gmail.com
  subject: Email Functionality Implementation
  body: Hi, Today i was learning how to write email functionality
  attachment: C:\Users\USER\OneDrive\Desktop\Collectionsss
