spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webapplication
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: developer@me123
            
server:
  port: 8890

email:
  enable: true
  to: bhoomikahm133@gmail.com
  from: hackestone@gmail.com
  subject: Email Functionality Implementation
  body: Hi, Today i was learning how to write email functionality
  attachment: C:\Users\USER\OneDrive\Desktop\Collectionsss